services:
  github-mcp-http:
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_MCP_GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_MCP_HOST=0.0.0.0
      - GITHUB_MCP_PORT=8080
      - GITHUB_MCP_GITHUB_READ_ONLY=false
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge